'use client';
import {FormEvent,useEffect,useMemo,useState} from 'react';
import type {Session} from '@supabase/supabase-js';
import {supabase} from '../lib/supabase';
type Sample={id:string;sample_name:string;received_at:string;product:string;requester:string|null;status:string};
type Catalog={id:string;name:string;standard:string|null;available_in_house:boolean};
type Test={id:string;sample_id:string;test_name:string;status:string;final_result:string|null;units:string|null};
type Equipment={id:string;code:string|null;name:string;status:string|null;expires_at:string|null};
const sections=['Resumen','Muestras','Ensayos','Datos crudos','Equipos'];
export default function LabApp(){
 const [session,setSession]=useState<Session|null>(null),[loading,setLoading]=useState(true),[section,setSection]=useState('Resumen');
 const [samples,setSamples]=useState<Sample[]>([]),[catalog,setCatalog]=useState<Catalog[]>([]),[tests,setTests]=useState<Test[]>([]),[equipment,setEquipment]=useState<Equipment[]>([]),[rawCount,setRawCount]=useState(0);
 const [modal,setModal]=useState<'sample'|'test'|'raw'|null>(null),[notice,setNotice]=useState('');
 useEffect(()=>{supabase.auth.getSession().then(({data})=>{setSession(data.session);setLoading(false)});const {data}=supabase.auth.onAuthStateChange((_e,s)=>setSession(s));return()=>data.subscription.unsubscribe()},[]);
 useEffect(()=>{if(session)refresh()},[session]);
 async function refresh(){const [s,c,t,e,r]=await Promise.all([supabase.from('samples').select('id,sample_name,received_at,product,requester,status').order('created_at',{ascending:false}),supabase.from('test_catalog').select('id,name,standard,available_in_house').order('name'),supabase.from('sample_tests').select('id,sample_id,test_name,status,final_result,units').order('created_at',{ascending:false}),supabase.from('equipment').select('id,code,name,status,expires_at').order('name'),supabase.from('raw_test_data').select('*',{count:'exact',head:true})]);setSamples(s.data||[]);setCatalog(c.data||[]);setTests(t.data||[]);setEquipment(e.data||[]);setRawCount(r.count||0)}
 function flash(t:string){setNotice(t);setTimeout(()=>setNotice(''),3500)}
 const sampleMap=useMemo(()=>Object.fromEntries(samples.map(s=>[s.id,s.sample_name])),[samples]);
 if(loading)return <div className="screen-center"><div className="loader"/>Preparando laboratorio…</div>;
 if(!session)return <Login/>;
 return <main className="app-shell"><aside className="sidebar"><Brand/ ><nav>{sections.map(x=><button key={x} className={section===x?'active':''} onClick={()=>setSection(x)}>{x}</button>)}</nav><div className="account"><small>SESIÓN ACTIVA</small><span>{session.user.email}</span><button onClick={()=>supabase.auth.signOut()}>Cerrar sesión</button></div></aside><section className="workspace"><header className="topbar"><div><p>{new Intl.DateTimeFormat('es-AR',{weekday:'long',day:'numeric',month:'long'}).format(new Date()).toUpperCase()}</p><h1>{section}</h1></div><button className="primary" onClick={()=>setModal('sample')}>+ Nueva muestra</button></header>
 {section==='Resumen'&&<Dashboard samples={samples} catalog={catalog} tests={tests} equipment={equipment} sampleMap={sampleMap} open={setModal} backup={()=>backup(flash)}/>}
 {section==='Muestras'&&<SampleTable samples={samples} open={()=>setModal('sample')}/>}
 {section==='Ensayos'&&<TestTable tests={tests} sampleMap={sampleMap} open={()=>setModal('test')}/>}
 {section==='Datos crudos'&&<RawPanel count={rawCount} open={()=>setModal('raw')} backup={()=>backup(flash)}/>}
 {section==='Equipos'&&<EquipmentTable data={equipment}/>}</section>
 {modal==='sample'&&<SampleForm session={session} catalog={catalog} close={()=>setModal(null)} done={()=>{setModal(null);refresh();flash('Muestra creada con ID automático')}}/>}
 {modal==='test'&&<TestForm session={session} samples={samples} catalog={catalog} close={()=>setModal(null)} done={()=>{setModal(null);refresh();flash('Ensayo registrado')}}/>}
 {modal==='raw'&&<RawForm session={session} tests={tests} sampleMap={sampleMap} close={()=>setModal(null)} done={()=>{setModal(null);refresh();flash('Datos crudos guardados')}}/>}
 {notice&&<div className="toast">{notice}</div>}</main>
}
function Brand(){return <div className="brand"><span>SG</span><div><strong>SEGOD</strong><small>Laboratorio</small></div></div>}
function Login(){const [email,setEmail]=useState(''),[password,setPassword]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false);async function submit(e:FormEvent){e.preventDefault();setBusy(true);const {error}=await supabase.auth.signInWithPassword({email,password});setBusy(false);if(error)setError('Correo o contraseña incorrectos')}return <main className="login"><section><Brand/><div><p>CONTROL TÉCNICO</p><h1>Resultados trazables.<br/>Datos siempre disponibles.</h1><span>Gestión segura de muestras, ensayos y mediciones crudas.</span></div></section><form onSubmit={submit}><p>ACCESO INTERNO</p><h2>Ingresar al laboratorio</h2><label>Correo<input type="email" value={email} onChange={e=>setEmail(e.target.value)} required/></label><label>Contraseña<input type="password" value={password} onChange={e=>setPassword(e.target.value)} required/></label>{error&&<b className="error">{error}</b>}<button className="primary" disabled={busy}>{busy?'Ingresando…':'Ingresar'}</button><small>Solicitá una cuenta al responsable técnico.</small></form></main>}
function Dashboard({samples,catalog,tests,equipment,sampleMap,open,backup}:{samples:Sample[];catalog:Catalog[];tests:Test[];equipment:Equipment[];sampleMap:Record<string,string>;open:(m:'sample'|'test'|'raw')=>void;backup:()=>void}){return <><div className="metrics"><Metric label="Muestras activas" value={samples.filter(s=>s.status!=='Finalizada').length} note={samples.length+' ingresos totales'}/><Metric label="Ensayos disponibles" value={catalog.length} note={catalog.filter(c=>c.available_in_house).length+' internos'}/><Metric label="Equipos registrados" value={equipment.length} note={equipment.filter(e=>e.status==='Apto').length+' aptos'}/></div><div className="content-grid"><article className="panel"><Heading eyebrow="TRABAJO RECIENTE" title="Muestras y órdenes"/>{samples.length?<div className="rows">{samples.slice(0,6).map(s=><div className="row" key={s.id}><div><strong>{s.sample_name}</strong><small>{s.product} · {s.requester||'Sin solicitante'}</small></div><Badge text={s.status}/></div>)}</div>:<Empty action={()=>open('sample')}/>}</article><aside className="panel quick"><Heading eyebrow="ACCESOS RÁPIDOS" title="Operaciones"/><button onClick={()=>open('test')}>Cargar ensayo <span>→</span></button><button onClick={()=>open('raw')}>Registrar dato crudo <span>→</span></button><button onClick={backup}>Exportar backup <span>↓</span></button>{tests.slice(0,2).map(t=><small key={t.id}>{sampleMap[t.sample_id]} · {t.test_name}</small>)}</aside></div></>}
function Metric({label,value,note}:{label:string;value:number;note:string}){return <article><span>{label}</span><strong>{value}</strong><small>{note}</small></article>}
function Heading({eyebrow,title}:{eyebrow:string;title:string}){return <div className="panel-head"><div><p>{eyebrow}</p><h2>{title}</h2></div></div>}
function Badge({text}:{text:string}){return <span className="badge">{text}</span>}
function Empty({action}:{action:()=>void}){return <div className="empty"><span>SEGOD · LAB</span><h3>El laboratorio está listo</h3><p>Registrá la primera muestra para asignarle un ID único y comenzar sus ensayos.</p><button className="primary" onClick={action}>Registrar muestra</button></div>}
function SampleTable({samples,open}:{samples:Sample[];open:()=>void}){return <article className="panel table-panel"><div className="panel-head"><Heading eyebrow="REGISTRO" title="Muestras y órdenes"/><button className="primary" onClick={open}>Nueva muestra</button></div><div className="table five"><div className="tr th"><span>ID</span><span>Ingreso</span><span>Producto</span><span>Solicitante</span><span>Estado</span></div>{samples.map(s=><div className="tr" key={s.id}><strong>{s.sample_name}</strong><span>{s.received_at}</span><span>{s.product}</span><span>{s.requester||'—'}</span><Badge text={s.status}/></div>)}</div></article>}
function TestTable({tests,sampleMap,open}:{tests:Test[];sampleMap:Record<string,string>;open:()=>void}){return <article className="panel table-panel"><div className="panel-head"><Heading eyebrow="RESULTADOS" title="Ensayos realizados"/><button className="primary" onClick={open}>Nuevo ensayo</button></div><div className="table four"><div className="tr th"><span>Muestra</span><span>Ensayo</span><span>Resultado</span><span>Estado</span></div>{tests.map(t=><div className="tr" key={t.id}><strong>{sampleMap[t.sample_id]||'—'}</strong><span>{t.test_name}</span><span>{t.final_result||'Pendiente'} {t.units||''}</span><Badge text={t.status}/></div>)}</div></article>}
function RawPanel({count,open,backup}:{count:number;open:()=>void;backup:()=>void}){return <div className="raw-layout"><article className="panel raw-hero"><Heading eyebrow="TRAZABILIDAD" title="Datos crudos"/><strong>{count}</strong><span>registros conservados</span><p className="body">Las mediciones se vinculan al UUID interno de la muestra y se guardan completas en JSON.</p><button className="primary" onClick={open}>Registrar mediciones</button></article><article className="panel backup-card"><Heading eyebrow="RESPALDO" title="Extraer toda la base"/><p className="body">Descargá muestras, ensayos, catálogos, equipos y datos crudos.</p><button className="secondary" onClick={backup}>Descargar backup JSON</button></article></div>}
function EquipmentTable({data}:{data:Equipment[]}){return <article className="panel table-panel"><Heading eyebrow="INVENTARIO" title="Equipos y elementos"/><div className="table four"><div className="tr th"><span>Código</span><span>Equipo</span><span>Estado</span><span>Vencimiento</span></div>{data.map(e=><div className="tr" key={e.id}><strong>{e.code||'—'}</strong><span>{e.name}</span><Badge text={e.status||'Sin estado'}/><span>{e.expires_at||'—'}</span></div>)}</div></article>}
function Modal({title,eyebrow,close,children}:{title:string;eyebrow:string;close:()=>void;children:React.ReactNode}){return <div className="modal-backdrop"><section className="modal"><header><Heading eyebrow={eyebrow} title={title}/><button onClick={close}>×</button></header>{children}</section></div>}
function Footer({close,busy}:{close:()=>void;busy:boolean}){return <footer><button type="button" className="secondary" onClick={close}>Cancelar</button><button className="primary" disabled={busy}>{busy?'Guardando…':'Guardar'}</button></footer>}
function SampleForm({session,catalog,close,done}:{session:Session;catalog:Catalog[];close:()=>void;done:()=>void}){const [busy,setBusy]=useState(false),[error,setError]=useState('');async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);const f=new FormData(e.currentTarget);const {error}=await supabase.from('samples').insert({received_at:f.get('date'),product:f.get('product'),requester:f.get('requester')||null,model_size_hand:f.get('model')||null,lot_batch_work_order:f.get('lot')||null,quantity_received:Number(f.get('qty')||0),requested_tests:f.get('test')||null,requested_standard:f.get('standard')||null,status:'Ingresada',location_and_storage:f.get('location')||null,notes:f.get('notes')||null,created_by:session.user.id});setBusy(false);if(error)setError(error.message);else done()}return <Modal title="Nueva muestra" eyebrow="INGRESO Y TRAZABILIDAD" close={close}><form className="form-grid" onSubmit={submit}><label>Fecha<input name="date" type="date" defaultValue={new Date().toISOString().slice(0,10)} required/></label><label>Producto<input name="product" required/></label><label>Solicitante<input name="requester"/></label><label>Modelo · Talle · Mano<input name="model"/></label><label>Lote · Partida · OP<input name="lot"/></label><label>Cantidad<input name="qty" type="number" min="0"/></label><label>Ensayo<select name="test"><option value="">Seleccionar</option>{catalog.map(c=><option key={c.id}>{c.name}</option>)}</select></label><label>Norma<input name="standard"/></label><label>Ubicación<input name="location"/></label><label className="wide">Observaciones<textarea name="notes"/></label>{error&&<b className="error wide">{error}</b>}<Footer close={close} busy={busy}/></form></Modal>}
function TestForm({session,samples,catalog,close,done}:{session:Session;samples:Sample[];catalog:Catalog[];close:()=>void;done:()=>void}){const [busy,setBusy]=useState(false),[error,setError]=useState('');async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget),c=catalog.find(x=>x.id===f.get('catalog'));if(!c)return;setBusy(true);const {error}=await supabase.from('sample_tests').insert({sample_id:f.get('sample'),test_catalog_id:c.id,test_name:c.name,applied_standard:c.standard,final_result:f.get('result')||null,units:f.get('units')||null,status:f.get('status'),notes:f.get('notes')||null,created_by:session.user.id});setBusy(false);if(error)setError(error.message);else done()}return <Modal title="Registrar ensayo" eyebrow="RESULTADO TÉCNICO" close={close}><form className="form-grid" onSubmit={submit}><label className="wide">Muestra<select name="sample" required><option value="">Seleccionar</option>{samples.map(s=><option key={s.id} value={s.id}>{s.sample_name} · {s.product}</option>)}</select></label><label className="wide">Ensayo<select name="catalog" required><option value="">Seleccionar</option>{catalog.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label>Resultado<input name="result"/></label><label>Unidades<input name="units"/></label><label>Estado<select name="status"><option>Pendiente</option><option>En curso</option><option>Finalizado</option><option>Revisado</option></select></label><label className="wide">Observaciones<textarea name="notes"/></label>{error&&<b className="error wide">{error}</b>}<Footer close={close} busy={busy}/></form></Modal>}
function RawForm({session,tests,sampleMap,close,done}:{session:Session;tests:Test[];sampleMap:Record<string,string>;close:()=>void;done:()=>void}){const [busy,setBusy]=useState(false),[error,setError]=useState(''),[json,setJson]=useState('{\n  "mediciones": [],\n  "observaciones": ""\n}');async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget),t=tests.find(x=>x.id===f.get('test'));if(!t)return;let raw;try{raw=JSON.parse(json)}catch{setError('JSON no válido');return}setBusy(true);const {error}=await supabase.from('raw_test_data').insert({sample_test_id:t.id,sample_id:t.sample_id,data_type:f.get('type'),sequence_no:Number(f.get('seq')||1),raw_values:raw,captured_by:session.user.id});setBusy(false);if(error)setError(error.message);else done()}return <Modal title="Datos crudos" eyebrow="MEDICIONES ORIGINALES" close={close}><form className="form-grid" onSubmit={submit}><label className="wide">Ensayo<select name="test" required><option value="">Seleccionar</option>{tests.map(t=><option value={t.id} key={t.id}>{sampleMap[t.sample_id]} · {t.test_name}</option>)}</select></label><label>Tipo<select name="type"><option>medicion</option><option>ph</option><option>impacto</option><option>corte_cuchilla</option><option>perforacion</option><option>rasgado</option><option>abrasion</option></select></label><label>Secuencia<input name="seq" type="number" min="1" defaultValue="1"/></label><label className="wide">Valores JSON<textarea className="code" rows={9} value={json} onChange={e=>setJson(e.target.value)}/></label>{error&&<b className="error wide">{error}</b>}<Footer close={close} busy={busy}/></form></Modal>}
async function backup(flash:(t:string)=>void){const names=['staff','test_catalog','equipment','samples','sample_tests','raw_test_data'],out:Record<string,unknown>={exported_at:new Date().toISOString()};for(const name of names){const {data,error}=await supabase.from(name).select('*');if(error){flash('No se pudo exportar');return}out[name]=data}const u=URL.createObjectURL(new Blob([JSON.stringify(out,null,2)],{type:'application/json'})),a=document.createElement('a');a.href=u;a.download='segod-backup-'+new Date().toISOString().slice(0,10)+'.json';a.click();URL.revokeObjectURL(u);flash('Backup descargado')}
