create index if not exists staff_auth_user_idx on public.staff(auth_user_id);
create index if not exists samples_modified_by_idx on public.samples(modified_by);
create index if not exists tests_assigned_to_idx on public.sample_tests(assigned_to);
create index if not exists tests_equipment_id_idx on public.sample_tests(equipment_id);
create index if not exists tests_modified_by_idx on public.sample_tests(modified_by);
create index if not exists tests_voided_by_idx on public.sample_tests(voided_by);
create index if not exists tests_replacement_idx on public.sample_tests(replacement_test_id);
create index if not exists raw_equipment_id_idx on public.raw_test_data(equipment_id);
create index if not exists raw_modified_by_idx on public.raw_test_data(modified_by);
create index if not exists raw_voided_by_idx on public.raw_test_data(voided_by);
create index if not exists raw_replacement_idx on public.raw_test_data(replacement_raw_id);
create index if not exists training_staff_idx on public.staff_training(staff_id);
create index if not exists training_created_by_idx on public.staff_training(created_by);
create index if not exists equipment_events_equipment_idx on public.equipment_events(equipment_id);
create index if not exists equipment_events_created_by_idx on public.equipment_events(created_by);
create index if not exists documents_created_by_idx on public.documents(created_by);
create index if not exists audit_changed_by_idx on public.audit_log(changed_by);
create index if not exists alerts_resolved_by_idx on public.lab_alerts(resolved_by);

drop policy if exists training_manage on public.staff_training;
create policy training_insert on public.staff_training for insert to authenticated with check (private.has_lab_permission('manage'));
create policy training_update on public.staff_training for update to authenticated using (private.has_lab_permission('manage')) with check (private.has_lab_permission('manage'));
drop policy if exists equipment_events_manage on public.equipment_events;
create policy equipment_events_insert on public.equipment_events for insert to authenticated with check (private.has_lab_permission('manage'));
create policy equipment_events_update on public.equipment_events for update to authenticated using (private.has_lab_permission('manage')) with check (private.has_lab_permission('manage'));
drop policy if exists documents_manage on public.documents;
create policy documents_insert on public.documents for insert to authenticated with check (private.has_lab_permission('documents'));
create policy documents_update on public.documents for update to authenticated using (private.has_lab_permission('documents')) with check (private.has_lab_permission('documents'));
drop policy if exists alerts_manage on public.lab_alerts;
create policy alerts_insert on public.lab_alerts for insert to authenticated with check (private.has_lab_permission('manage'));
create policy alerts_update on public.lab_alerts for update to authenticated using (private.has_lab_permission('manage')) with check (private.has_lab_permission('manage'));
